Fix "rake scripts" when running on Windows.
cmd.exe does not recognize backslash as an escape character,
leading to errors like the following:

    error: stray '\' in program
    note: in definition of macro 'UNITY_OUTPUT_CHAR_HEADER_DECLARATION'

It does, however, recognize double quotes, so we can use those as
a portable method of escaping special characters on both Windows
and UNIX.